@startuml
|フロント|
:会員登録;
|アプリケーション|
:会員登録;
|DB|
:会員情報DB]
|アプリケーション|
:リダイレクト;
|フロント|
:ログイン画面]
repeat
    :ログイン;
    |アプリケーション|
    :認証;
    |DB|
    :会員管理]
|アプリケーション|
repeat while (認証成功)
|フロント|
:トップページ]
repeat
    :目標入力;
    |アプリケーション|
    :入力内容;
    if (登録導線) then (後続目標)
        |DB|
        :目標管理]
        :紐付け管理]
    else (新規目標)
        |DB|
        :目標管理]
    endif
    |アプリケーション|
    :取得;
    |フロント|
    :目標一覧]
    :評価入力;
    |アプリケーション|
    :入力内容;
    |DB|
    :評価管理]
    |フロント|
    if (後続目標の登録) then (しない)
        end
    else (する)
    endif
repeat while (登録画面遷移)
kill
@enduml